export const IconName = {
  EYE: "eye",
  EYE_OFF: "eye-off",
  SPINNER: "spinner",
  ALERT: "alert",
  DASHBOARD: "dashboard",
  CASES: "cases",
  INBOX: "inbox",
  DERIVATIONS: "derivations",
  AI_REVIEW: "ai-review",
  DATASET: "dataset",
  MODELS: "models",
  LABELS: "labels",
  COMPETENCIES: "competencies",
  ORGANIZATIONS: "organizations",
  USERS: "users",
  EVIDENCE: "evidence",
  BELL: "bell",
  AUDIT: "audit",
  CHEVRON_DOWN: "chevron-down",
  SIDEBAR_CLOSE: "sidebar-close",
  SIDEBAR_OPEN: "sidebar-open",
  LOGOUT: "logout",
  CALENDAR: "calendar",
} as const;
export type IconName = (typeof IconName)[keyof typeof IconName];
