export const IconName = {
  EYE: "eye",
  EYE_OFF: "eye-off",
  SPINNER: "spinner",
  ALERT: "alert",
  DASHBOARD: "dashboard",
  CASES: "cases",
  INBOX: "inbox",
  DERIVATIONS: "derivations",
  AI_REVIEW: "ai-review",
  DATASET: "dataset",
  MODELS: "models",
  LABELS: "labels",
  COMPETENCIES: "competencies",
  ORGANIZATIONS: "organizations",
  USERS: "users",
  EVIDENCE: "evidence",
  BELL: "bell",
  AUDIT: "audit",
  CHEVRON_DOWN: "chevron-down",
  CHEVRON_LEFT: "chevron-left",
  CHEVRON_RIGHT: "chevron-right",
  ARROW_UP: "arrow-up",
  ARROW_DOWN: "arrow-down",
  ARROWS_UP_DOWN: "arrows-up-down",
  SIDEBAR_CLOSE: "sidebar-close",
  SIDEBAR_OPEN: "sidebar-open",
  LOGOUT: "logout",
  CALENDAR: "calendar",
  SEARCH: "search",
  MENU: "menu",
  CLOSE: "close",
  QR_CODE: "qr-code",
  DOWNLOAD: "download",
} as const;
export type IconName = (typeof IconName)[keyof typeof IconName];
