import {
  LucideBell,
  LucideBuilding2,
  LucideCalendarDays,
  LucideArrowDown,
  LucideArrowUp,
  LucideArrowUpDown,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleAlert,
  LucideCpu,
  LucideDatabase,
  LucideEye,
  LucideEyeOff,
  LucideFileImage,
  LucideFolderOpen,
  LucideHistory,
  LucideInbox,
  LucideLayoutDashboard,
  LucideLoaderCircle,
  LucideLogOut,
  LucideMenu,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucideScale,
  LucideSearch,
  LucideSend,
  LucideSparkles,
  LucideTag,
  LucideUsers,
  LucideX,
  type LucideIconData,
} from "@lucide/angular";
import { IconName } from "@/shared/enums/icon-name.enum";

export const ICONS: Record<IconName, LucideIconData> = {
  [IconName.EYE]: LucideEye.icon,
  [IconName.EYE_OFF]: LucideEyeOff.icon,
  [IconName.SPINNER]: LucideLoaderCircle.icon,
  [IconName.ALERT]: LucideCircleAlert.icon,
  [IconName.DASHBOARD]: LucideLayoutDashboard.icon,
  [IconName.CASES]: LucideFolderOpen.icon,
  [IconName.INBOX]: LucideInbox.icon,
  [IconName.DERIVATIONS]: LucideSend.icon,
  [IconName.AI_REVIEW]: LucideSparkles.icon,
  [IconName.DATASET]: LucideDatabase.icon,
  [IconName.MODELS]: LucideCpu.icon,
  [IconName.LABELS]: LucideTag.icon,
  [IconName.COMPETENCIES]: LucideScale.icon,
  [IconName.ORGANIZATIONS]: LucideBuilding2.icon,
  [IconName.USERS]: LucideUsers.icon,
  [IconName.EVIDENCE]: LucideFileImage.icon,
  [IconName.BELL]: LucideBell.icon,
  [IconName.AUDIT]: LucideHistory.icon,
  [IconName.CHEVRON_DOWN]: LucideChevronDown.icon,
  [IconName.CHEVRON_LEFT]: LucideChevronLeft.icon,
  [IconName.CHEVRON_RIGHT]: LucideChevronRight.icon,
  [IconName.ARROW_UP]: LucideArrowUp.icon,
  [IconName.ARROW_DOWN]: LucideArrowDown.icon,
  [IconName.ARROWS_UP_DOWN]: LucideArrowUpDown.icon,
  [IconName.SIDEBAR_CLOSE]: LucidePanelLeftClose.icon,
  [IconName.SIDEBAR_OPEN]: LucidePanelLeftOpen.icon,
  [IconName.LOGOUT]: LucideLogOut.icon,
  [IconName.CALENDAR]: LucideCalendarDays.icon,
  [IconName.SEARCH]: LucideSearch.icon,
  [IconName.MENU]: LucideMenu.icon,
  [IconName.CLOSE]: LucideX.icon,
};
